language: php
php:
  - '7.0'
services:
  - redis-server
install:
  - composer install
script:
  - ./vendor/bin/phpcs --standard=PSR2 --colors --extensions=php,inc,lib --ignore=vendor ./
  - ./vendor/bin/phpunit --debug
